---
sudo: false

language: ruby

cache: bundler

rvm:
  - 2.6.3
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

before_install: gem install bundler -v 2.0.2

bundler_args: --without development --jobs=3 --retry=3

before_script:
  - ./cc-test-reporter before-build

script:
  - rake

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT